- app/Http/Controllers/homeController.php
- database/migrations/2021_11_07_013202_create_desarrollas_table.php
- resources/views/registro.blade.php
- routes/web.php
resolve #14 
resolve #28 
Pagina de registro creada.
Observaciones quitadas.
Proyecto sin bootstrap descargado.
Llave primaria para la tabla desarrolla.
> Pagina de registro creada 

- app/Http/Controllers/homeController.php
- app/Http/Controllers/registroController.php
- app/Models/Persona.php
- resources/views/registro.blade.php
- routes/web.php
> registro de personas guardado

- app/Http/Controllers/Auth/ConfirmPasswordController.php
- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/loginController.php
- app/Http/Controllers/sessionController.php
- resources/views/layouts/home_plantilla.blade.php
- routes/web.php
> logout agregado

- app/Http/Kernel.php
- app/Http/Middleware/DirectorMiddleware.php
- routes/web.php
> Add DirectorMiddleware

- database/seeders/RolSeeder.php
Resolve #41 
Migrar y seedear a Heroku :3
> Secretaria cambiado a administrador

- app/Http/Controllers/homeController.php
- resources/views/alumno.blade.php
- routes/web.php
> pagina de alumno agregada

- resources/views/alumno.blade.php
- resources/views/layouts/datosPersonales_plantilla.blade.php
> Plantilla de datos personales creada - Revision de action form

- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/homeController.php
- resources/views/layouts/datosPersonales_plantilla.blade.php
- resources/views/newAdministrativo.blade.php
- routes/web.php
> Pagina para registrar Administrado finalizada

- app/Http/Controllers/homeController.php
- resources/views/alumno.blade.php
- resources/views/newProfesor.blade.php
- routes/web.php
> pagina de registro profesor subida

- routes/web.php
resolve #66 
Issue #66 
Cabe mencionar que un mejor metodo de organizacion de carpetas-views seria uno en el que:
Existen carpetas que contienen las views de las cuales los distintos tipos de usuarios (y solo un tipo de usuario) tendrá ACCESO.
Ejemplo:
-Director:
*Director_HomePage.blade.php (aun no creada, sugerencia de creacion en el futuro)
*newAdministrador.blade.php (vista de registro de nuevos administradores SOLO accesible por el director)
*registro.blade.php (vista de registro de personas actualmente solo accesible por el director)
-Administrativos:
*administrativo.blade.php (homePage del administrativo)
*materiaRegistro.blade.php (Vista de registro de materias).
y asi sucesivamente...
> Creacion de carpetas de organizacion

- resources/views/cursoCreate.blade.php
> vista añadida

- resources/views/alumno.blade.php
- resources/views/layouts/datosPersonales_plantilla.blade.php
- resources/views/profesor.blade.php
> informacion academica agregada

- app/Http/Controllers/alumnoController.php
- resources/views/Alumno/show.blade.php
- resources/views/welcome.blade.php
- routes/web.php
Resolve #81 
Listuuuuuu Revisar bien por si me equivoque en algo :3
> Crud Read de Alumno terminado - Siuuuuuuuu

- app/Http/Controllers/homeController.php
- resources/views/Inscripcion/inscripcion.blade.php
- routes/web.php
> Add inscripcion page

- app/Http/Controllers/alumnoController.php
> crud_delete_alumno hecho

- app/Http/Controllers/alumnoController.php
- resources/views/Alumno/edit.blade.php
- resources/views/layouts/datosPersonales_plantilla.blade.php
- resources/views/welcome.blade.php
resolve #82 
ISSUE_NUMBER : 82
> crud_edit_alumno hecho

- app/Http/Controllers/alumnoController.php
- resources/views/layouts/home_plantilla.blade.php
- resources/views/layouts/master.blade.php
resolve #107 
ISSUE_NUMBER #107
> Fix alert messages

- app/Http/Controllers/alumnoController.php
resolve #109 
ISSUE_NUMBER #109
> Fix alumno destroy

- app/Http/Controllers/administrativoController.php
- resources/views/Administrativo/administrativo.blade.php
- resources/views/Administrativo/create.blade.php
- resources/views/Administrativo/edit.blade.php
- resources/views/Administrativo/index.blade.php
- resources/views/Administrativo/show.blade.php
- routes/web.php
> crud de administrativo subido

- app/Http/Controllers/pagoMensualidadController.php
- app/Models/pagoMensualidad.php
- app/Models/pagos.php
- resources/views/PagoMensualidad/create.blade.php
- resources/views/PagoMensualidad/index.blade.php
- resources/views/PagoMensualidad/show.blade.php
- routes/web.php
> Crud pago mensualidad realizado

- app/Http/Controllers/cursoController.php
- app/Http/Controllers/usuarioController.php
- app/Models/User.php
- resources/views/Usuario/index.blade.php
- resources/views/Usuario/show.blade.php
resolve #113 
ISSUE_NUMBER :13
> crud-usuario-hecho

- app/Http/Controllers/homeController.php
> home middleware agregado

- app/Http/Controllers/inscripcionController.php
- app/Http/Controllers/notasController.php
- public/css/sidebar-blue-cristo.css
> error de notas corregido

- app/Http/Controllers/notasController.php
- resources/views/Nota/modificacion.blade.php
> error de notas solucionado
